(function(g){var window=this;var iAa=function(a,b){return g.Sb(a,b)},Y5=function(a){g.Gm(a,"zx",g.xb());
return a},Z5=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Jm(a.g,b,c)},jAa=function(a,b){var c=[];
g.kk(b,function(a){try{var b=g.$C.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ZC(b)&&c.push(a):c.push(a)},a);
return c},kAa=function(a,b){var c=jAa(a,b);
(0,g.C)(c,function(a){g.$C.prototype.remove.call(this,a)},a)},lAa=function(){var a=g.FG;
kAa(a,a.g.ee(!0))},mAa=function(a,b,c,d){var e=new g.xm(null,void 0);
a&&g.ym(e,a);b&&g.zm(e,b);c&&g.Am(e,c);d&&g.Bm(e,d);return e},nAa=function(a){g.PF[a]&&(a=g.PF[a],(0,g.C)(a,function(a){g.NF[a]&&delete g.NF[a]}),a.length=0)},oAa=function(a){var b=g.MF();
if(b)if(b.clear(a),a)nAa(a);else for(var c in g.PF)nAa(c)},$5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.rm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",pAa(this,a.capabilities||""),qAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},pAa=function(a,b){a.capabilities.clear();
(0,g.Gd)(b.split(","),g.Da(iAa,rAa)).forEach(function(b){a.capabilities.add(b)})},qAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},a6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},b6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},sAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},tAa=function(a){return new a6(a)},uAa=function(a){return g.xa(a)?(0,g.H)(a,tAa):[]},c6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},d6=function(a){return g.xa(a)?"["+(0,g.H)(a,c6).join(",")+"]":"null"},e6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},vAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},f6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},g6=function(a,b){return g.Ja(a,function(a){return b6(a,b)})},h6=function(){var a=g.IG("yt-remote-connected-devices")||[];
g.fb(a);return a},wAa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},xAa=function(a){g.HG("yt-remote-connected-devices",a,86400)},j6=function(){if(i6)return i6;
var a=g.IG("yt-remote-device-id");a||(a=e6(),g.HG("yt-remote-device-id",a,31536E3));for(var b=h6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return i6=d},k6=function(){var a=h6(),b=j6();
g.Na(a,b);g.NG()&&g.ib(a,b);a=wAa(a);if(g.Oa(a))try{g.LG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.MG("remote_sid",a.join(","),-1)}catch(c){}},yAa=function(){return g.IG("yt-remote-session-browser-channel")},zAa=function(){return g.IG("yt-remote-local-screens")||[]},AAa=function(){g.HG("yt-remote-lounge-token-expiration",!0,86400)},BAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(zAa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.gm)(c,function(a){return!g.Na(b,a)})&&AAa();
g.HG("yt-remote-local-screens",a,31536E3)},CAa=function(a,b){g.HG("yt-remote-session-browser-channel",a);
g.HG("yt-remote-session-screen-id",b);var c=h6(),d=j6();g.Na(c,d)||c.push(d);xAa(c);k6()},l6=function(a){a||(g.JG("yt-remote-session-screen-id"),g.JG("yt-remote-session-video-id"));
k6();a=h6();g.Sa(a,j6());xAa(a)},DAa=function(){if(!m6){var a=g.fD();
a&&(m6=new g.UC(a))}return m6?!!m6.get("yt-remote-use-staging-server"):!1},EAa=function(){var a=window.document.createElement("a");
g.Vc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},FAa=function(a,b){var c=g.yd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Wc(c,g.Zd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},GAa=function(){var a=EAa(),b=window.document.getElementById(a),c=b&&g.aF(b,"loaded");
c||b&&!c||(b=FAa(a,function(){g.aF(b,"loaded")||(g.$E(b,"loaded","true"),g.TF(a),g.OD(g.Da(oAa,a),0))}))},n6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},HAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},o6=function(a){a.length?IAa(a.shift(),function(){o6(a)}):p6()},JAa=function(a){return"chrome-extension://"+a+q6},IAa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},r6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},p6=function(){var a=HAa();
a&&a(!1,"No cast extension found")},s6=function(){if(KAa){var a=2,b=HAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;IAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",p6,c)}},LAa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(s6(),a({command:"cast.sender.init"}))},MAa=function(){s6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);o6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+q6,"//www.gstatic.com/eureka/clank"+q6])},t6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.uc=b;this.B=(0,g.z)(this.bI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},u6=function(){},v6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Nm(this);this.l=new g.qg;this.l.setInterval(250)},OAa=function(a,b,c){a.pj=1;
a.ih=Y5(b.clone());a.Gi=c;a.C=!0;NAa(a,null)},w6=function(a,b,c,d,e){a.pj=1;
a.ih=Y5(b.clone());a.Gi=null;a.C=c;e&&(a.qC=!1);NAa(a,d)},NAa=function(a,b){a.Sj=(0,g.G)();
x6(a);a.Ah=a.ih.clone();Z5(a.Ah,"t",a.D);a.Tl=0;a.Pc=a.g.Gq(a.g.Ml()?b:null);0<a.lr&&(a.Wo=new g.Qk((0,g.z)(a.FD,a,a.Pc),a.lr));a.A.R(a.Pc,"readystatechange",a.eT);var c=a.gi?g.Zb(a.gi):{};a.Gi?(a.Fp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Pc.send(a.Ah,a.Fp,a.Gi,c)):(a.Fp="GET",a.qC&&!g.ud&&(c.Connection="close"),a.Pc.send(a.Ah,a.Fp,null,c));a.g.tf(1)},RAa=function(a,b,c){for(var d=!0;!a.Ph&&a.Tl<c.length;){var e=PAa(a,c);
if(e==y6){4==b&&(a.jh=4,z6(15),d=!1);break}else if(e==QAa){a.jh=4;z6(16);d=!1;break}else A6(a,e)}4==b&&0==c.length&&(a.jh=1,z6(17),d=!1);a.xf=a.xf&&d;d||(B6(a),C6(a))},PAa=function(a,b){var c=a.Tl,d=b.indexOf("\n",c);
if(-1==d)return y6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return QAa;d+=1;if(d+c>b.length)return y6;var e=b.substr(d,c);a.Tl=d+c;return e},TAa=function(a,b){a.Sj=(0,g.G)();
x6(a);var c=b?window.location.hostname:"";a.Ah=a.ih.clone();g.Gm(a.Ah,"DOMAIN",c);g.Gm(a.Ah,"t",a.D);try{a.yf=new window.ActiveXObject("htmlfile")}catch(n){B6(a);a.jh=7;z6(22);C6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in D6)k=D6[l];else if(l in SAa)k=D6[l]=SAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=D6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Xc(g.sc("b/12014412"),d);a.yf.open();a.yf.write(g.Nc(c));a.yf.close();a.yf.parentWindow.m=(0,g.z)(a.iS,a);a.yf.parentWindow.d=(0,g.z)(a.HB,a,!0);a.yf.parentWindow.rpcClose=(0,g.z)(a.HB,a,!1);c=a.yf.createElement("DIV");a.yf.parentWindow.document.body.appendChild(c);d=g.Ec(a.Ah.toString());d=g.pb(g.Bc(d));d=g.Xc(g.sc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Nc(d);
a.g.tf(1)},x6=function(a){a.Vu=(0,g.G)()+a.B;
UAa(a,a.B)},UAa=function(a,b){if(null!=a.mk)throw Error("WatchDog timer not null");
a.mk=E6((0,g.z)(a.zS,a),b)},F6=function(a){a.mk&&(g.w.clearTimeout(a.mk),a.mk=null)},C6=function(a){a.g.Qx()||a.Ph||a.g.Ko(a)},B6=function(a){F6(a);
g.Xe(a.Wo);a.Wo=null;a.l.stop();g.Tm(a.A);if(a.Pc){var b=a.Pc;a.Pc=null;b.abort();b.dispose()}a.yf&&(a.yf=null)},A6=function(a,b){try{a.g.AB(a,b),a.g.tf(4)}catch(c){}},WAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;VAa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){WAa(a,b,c,d,f)},f)})}},VAa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{G6(d),c(!0)}catch(e){}};
d.onerror=function(){try{G6(d),c(!1)}catch(e){}};
d.onabort=function(){try{G6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{G6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},G6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},XAa=function(a){this.g=a;
this.l=new u6},YAa=function(a){var b=H6(a.g,a.sk,"/mail/images/cleardot.gif");
Y5(b);WAa(b.toString(),5E3,(0,g.z)(a.nH,a),3,2E3);a.tf(1)},J6=function(a){var b=a.g.H;
if(null!=b)z6(5),b?(z6(11),I6(a.g,a,!1)):(z6(12),I6(a.g,a,!0));else if(a.se=new v6(a,void 0,void 0,void 0),a.se.gi=a.ir,b=a.g,b=H6(b,b.Ml()?a.Pk:null,a.kr),z6(5),!g.sd||g.oc(10))Z5(b,"TYPE","xmlhttp"),w6(a.se,b,!1,a.Pk,!1);else{Z5(b,"TYPE","html");var c=a.se;a=!!a.Pk;c.pj=3;c.ih=Y5(b.clone());TAa(c,a)}},K6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new u6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},ZAa=function(a,b){this.g=a;
this.map=b;this.context=null},$Aa=function(a){g.Ze.call(this,"statevent",a)},aBa=function(a,b){g.Ze.call(this,"timingevent",a);
this.size=b},bBa=function(a){g.Ze.call(this,"serverreachability",a)},eBa=function(a){cBa(a);
if(3==a.g){var b=a.yl++,c=a.zn.clone();g.Gm(c,"SID",a.o);g.Gm(c,"RID",b);g.Gm(c,"TYPE","terminate");L6(a,c);b=new v6(a,a.o,b,void 0);b.pj=2;b.ih=Y5(c.clone());(new window.Image).src=b.ih;b.Sj=(0,g.G)();x6(b)}dBa(a)},fBa=function(a){a.IH(1,0);
a.zn=H6(a,null,a.gr);M6(a)},cBa=function(a){a.Yg&&(a.Yg.abort(),a.Yg=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);N6(a);a.Qd&&(a.Qd.cancel(),a.Qd=null);a.ah&&(g.w.clearTimeout(a.ah),a.ah=null)},gBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new ZAa(a.dO++,b));2!=a.g&&3!=a.g||M6(a)},M6=function(a){a.Qd||a.ah||(a.ah=E6((0,g.z)(a.FB,a),0),a.hj=0)},iBa=function(a,b){if(1==a.g){if(!b){a.yl=Math.floor(1E5*Math.random());
var c=a.yl++,d=new v6(a,"",c,void 0);d.gi=null;var e=O6(a),f=a.zn.clone();g.Gm(f,"RID",c);g.Gm(f,"CVER","1");L6(a,f);OAa(d,f,e);a.Qd=d;a.g=2}}else 3==a.g&&(b?hBa(a,b):0==a.l.length||a.Qd||hBa(a))},hBa=function(a,b){if(b)if(6<a.Rh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.yl-1;var d=O6(a)}else c=b.F,d=b.Gi;else c=a.yl++,d=O6(a);var e=a.zn.clone();g.Gm(e,"SID",a.o);g.Gm(e,"RID",c);g.Gm(e,"AID",a.Cj);L6(a,e);c=new v6(a,a.o,c,a.hj+1);c.gi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Qd=c;OAa(c,e,d)},L6=function(a,b){if(a.qd){var c=a.qd.yx();
c&&g.Jb(c,function(a,c){g.Gm(b,c,a)})}},O6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Rh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Rh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},jBa=function(a){a.tc||a.pg||(a.D=1,a.pg=E6((0,g.z)(a.EB,a),0),a.Wi=0)},P6=function(a){if(a.tc||a.pg||3<=a.Wi)return!1;
a.D++;a.pg=E6((0,g.z)(a.EB,a),kBa(a,a.Wi));a.Wi++;return!0},I6=function(a,b,c){a.Ep=c;
a.hf=b.xg;a.C||fBa(a)},N6=function(a){null!=a.Th&&(g.w.clearTimeout(a.Th),a.Th=null)},kBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Q6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.aU,a);c||(c=new g.xm("//www.google.com/images/cleardot.gif"),Y5(c));VAa(c.toString(),1E4,d)}else z6(2);lBa(a,b)},lBa=function(a,b){a.g=0;
a.qd&&a.qd.rw(b);dBa(a);cBa(a)},dBa=function(a){a.g=0;
a.hf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.uq();else{g.Wa(a.A);var b=g.Wa(a.l);a.A.length=0;a.l.length=0;a.qd.uq(b)}},H6=function(a,b,c){var d=g.Hm(c);
if(""!=d.l)b&&g.zm(d,b+"."+d.l),g.Am(d,d.B);else{var e=window.location;d=mAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ck&&g.Jb(a.Ck,function(a,b){g.Gm(d,b,a)});
g.Gm(d,"VER",a.Rh);L6(a,d);return d},E6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},z6=function(a){R6.dispatchEvent(new $Aa(R6,a))},mBa=function(){},nBa=function(a,b){this.action=a;
this.params=b||{}},T6=function(a,b){g.K.call(this);
this.g=new g.$t(this.o,0,this);g.M(this,this.g);this.l=this.uc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;S6(this)},S6=function(a){a.g.stop();
a.uc=5E3+2E4*Math.random()},U6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.TC;this.l=new T6(this.FU,this);this.g=this.Za=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},oBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ep,sessionId:a.g.o,arrayId:a.g.Cj}},pBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&iBa(a.g),eBa(a.g));a.F=0},V6=function(a){return!!a.g&&3==a.g.g},qBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},W6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},X6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Qg(c+b,{})},Y6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Da(a.A,d,!0),onError:g.Da(a.o,e),ud:g.Da(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.lE(b,a)},uBa=function(){var a=rBa;
sBa();Z6.push(a);tBa(Z6)},$6=function(a,b){sBa();
var c=Z6,d=vBa(a,String(b));g.Oa(c)?wBa(d):(tBa(c),(0,g.C)(c,function(a){a(d)}))},sBa=function(){Z6||(Z6=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",Z6,void 0))},wBa=function(a){var b=(a7+1)%50;
a7=b;b7[b]=a;c7||(c7=49==b)},tBa=function(a){var b=b7;
if(b[0]){var c=a7,d=c7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
b7=Array(50);a7=-1;c7=!1}},vBa=function(a,b){var c=((0,g.G)()-xBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},d7=function(a){g.FF.call(this);
this.D=a;this.g=[]},yBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},zBa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Gd)(a.g,function(a){return!!f6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=yBa(a,b[d])||c;return c},ABa=function(a,b){var c=a.g.length;
a.g=(0,g.Gd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},e7=function(a,b,c,d){g.FF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},g7=function(a){d7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;f7(this);this.info("Initializing with "+d6(this.g))},BBa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=X6(a.o,"/pairing/get_lounge_token_batch");
Y6(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.nI,a),(0,g.z)(a.mI,a))}},f7=function(a){var b=uAa(zAa());
b=(0,g.Gd)(b,function(a){return!a.uuid});
return zBa(a,b)},h7=function(a,b){BAa((0,g.H)(a.g,sAa));
b&&AAa()},j7=function(a,b){g.FF.call(this);
this.C=b;var c=g.IG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;i7("Initialized with "+g.xg(this.g))},CBa=function(a,b,c){var d=X6(a.B,"/pairing/get_screen_availability");
Y6(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},k7=function(a,b){a:if(g.Nb(b)!=g.Nb(a.g))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(i7("Updated online screens: "+g.xg(a.g)),a.g=b,a.P("screenChange"));DBa(a)},l7=function(a){(0,window.isNaN)(a.o)||g.QD(a.o);
a.o=g.OD((0,g.z)(a.hu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},i7=function(a){$6("OnlineScreenService",a)},EBa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},DBa=function(a){a=g.Pb(g.Kb(a.g,function(a){return a}));
g.fb(a);a.length?g.HG("yt-remote-online-screen-ids",a.join(","),60):g.JG("yt-remote-online-screen-ids")},m7=function(a){d7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};FBa(this)},HBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?g6(k,c):null)||g6(k,b)){k.uuid=b;var l=n7(a,k);CBa(a.l,l,function(a){e(a?l:null)})}else c?GBa(a,c,(0,g.z)(function(a){var f=n7(this,new a6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));CBa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},IBa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},GBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.lE(X6(a.C,"/pairing/get_lounge_token_batch"),e)},JBa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+d6(a.g))},FBa=function(a){o7(a);
a.o=new g7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.DI,a));JBa(a);a.A=uAa(g.IG("yt-remote-automatic-screen-cache")||[]);o7(a);a.info("Initializing automatic screens: "+d6(a.A));a.l=new j7(a.C,(0,g.z)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},n7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=g6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.HG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,sAa)));o7(a);a.B[b.uuid]=b.id;g.HG("yt-remote-device-id-map",a.B,31536E3);return b},o7=function(a){a.B=g.IG("yt-remote-device-id-map")||{}},p7=function(a,b,c){g.FF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},q7=function(a,b){$6(a.L,b)},r7=function(a,b){p7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.LU,this);this.B=(0,g.z)(this.JS,this);this.A=g.OD((0,g.z)(function(){KBa(this,null)},this),12E4)},LBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){q7(this,"Failed to send message: getMdxSessionStatus.")},a)):q7(a,"Sending yt message without session: "+g.xg(b))},KBa=function(a,b){g.QD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Lo,a),d=(0,g.z)(a.qe,a);a.Jx(b,c,d,5)}}else a.qe(Error("Waiting for session status timed out."))},s7=function(a,b,c){p7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.OU,this);this.g=g.y},MBa=function(a){a.g=a.H.MD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Lo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.qe(a)},a))},NBa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}DAa()&&(b.env_useStageMdx=1);return g.Og(b)},t7=function(a,b){p7.call(this,a,b,"ManualSession");
this.g=g.OD((0,g.z)(this.Dj,this,null),150)},u7=function(a,b,c,d){g.FF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.pR,this)},OBa=function(a,b){return b?g.Ja(a.o,function(a){return b6(b,a.label)},a):null},v7=function(a){$6("Controller",a)},rBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},w7=function(a){return a.B||!!a.o.length||!!a.g},x7=function(a,b,c){b!=a.g&&(g.Xe(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.CB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Dj(null)):a.P("yt-remote-cast2-session-change",null))},PBa=function(a){var b=a.l.LD(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&b6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=OBa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},VBa=function(a,b,c,d,e,f,k){QBa()?RBa(b,e,f,k)&&(z7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?SBa(a,c):(window.__onGCastApiAvailable=function(b,d){b?SBa(a,c):(A7("Failed to load cast API: "+d),B7(!1),z7(!1),g.JG("yt-remote-cast-available"),g.JG("yt-remote-cast-receiver"),TBa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):GAa():r6("CriOS")?LAa():r6("Android")&&r6("Chrome/")&&window.navigator.presentation?MAa():window.chrome&&window.navigator.presentation&&!r6("Edge")?(s6(),o6(UBa.map(JAa))):p6())):y7("Cannot initialize because not running Chrome")},TBa=function(){y7("dispose");
var a=C7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);WBa(!1);g.RF(D7);D7.length=0},E7=function(){return!!g.IG("yt-remote-cast-installed")},XBa=function(){var a=g.IG("yt-remote-cast-receiver");
return a?a.friendlyName:null},YBa=function(){y7("clearCurrentReceiver");
g.JG("yt-remote-cast-receiver")},ZBa=function(){return E7()?C7()?C7().getCastSession():(A7("getCastSelector: Cast is not initialized."),null):(A7("getCastSelector: Cast API is not installed!"),null)},G7=function(){E7()?C7()?F7()?(y7("Requesting cast selector."),C7().requestSession()):(y7("Wait for cast API to be ready to request the session."),D7.push(g.QF("yt-remote-cast2-api-ready",G7))):A7("requestCastSelector: Cast is not initialized."):A7("requestCastSelector: Cast API is not installed!")},H7=
function(a,b){F7()?C7().setConnectedScreenStatus(a,b):A7("setConnectedScreenStatus called before ready.")},QBa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.LJ||a},$Ba=function(a,b){C7().init(a,b)},RBa=function(a,b,c,d){var e=!1;
C7()||(a=new u7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.HG("yt-remote-cast-available",a);g.UF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){y7("onReceiverSelected: "+a.friendlyName);
g.HG("yt-remote-cast-receiver",a);g.UF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){y7("onReceiverResumed: "+a.friendlyName);
g.HG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){y7("onSessionChange: "+c6(a));
a||g.JG("yt-remote-cast-receiver");g.UF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
y7("cloudview.createSingleton_: "+e);return e},C7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},SBa=function(a,b){B7(!0);
z7(!1);$Ba(a,function(a){a?(WBa(!0),g.TF("yt-remote-cast2-api-ready")):(A7("Failed to initialize cast API."),B7(!1),g.JG("yt-remote-cast-available"),g.JG("yt-remote-cast-receiver"),TBa());b(a)})},y7=function(a){$6("cloudview",a)},A7=function(a){$6("cloudview",a)},B7=function(a){y7("setCastInstalled_ "+a);
g.HG("yt-remote-cast-installed",a)},F7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},WBa=function(a){y7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},I7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Lf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},J7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},K7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},L7=function(a,b){a.F=b;
a.D=(0,g.G)()},M7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},N7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J7(a)},O7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.l);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Q7=function(a,b){g.FF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.jC;this.o=this.l=null;this.H=(0,g.z)(this.MO,this);this.D=(0,g.z)(this.Bl,this);this.F=(0,g.z)(this.LO,this);this.I=(0,g.z)(this.ZO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.bv,this),aCa(this))):c=3;0!=c&&(b?this.bv(c):g.OD((0,g.z)(function(){this.bv(c)},this),0));
var d=ZBa();d&&P7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},R7=function(a){return new I7(a.A.getPlayerContextData())},aCa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Da(this.lR,a),this))},a)},bCa=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},S7=function(a,b){50>a.B.Lc()&&g.lC(a.B,b)},U7=function(a,b,c){var d=R7(a);
L7(d,c);-1E3!=d.g&&(d.g=b);T7(a,d)},V7=function(a,b,c){a.A.sendMessage(b,c)},T7=function(a,b){bCa(a);
a.A.setPlayerContextData(O7(b));aCa(a)},P7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Bl(null));
a.o=b;a.o&&($6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Bl(a.o.media[0]))},cCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=R7(a);b.contentId!=d.videoId&&$6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;L7(d,a.l.getEstimatedTime());T7(a,d)}else $6("CP","No cast media video. Ignoring state update.")},W7=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),V7(this,b,c))},a)},X7=function(a,b,c){g.FF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.V=[];this.A=this.D=this.o=this.bb=this.g=null;this.na=a;this.V.push(g.pF(window,"beforeunload",(0,g.z)(this.eI,this)));this.l=[];this.bb=new I7;this.X=b.id;this.g=dCa(this,c);this.g.subscribe("handlerOpened",this.QO,this);this.g.subscribe("handlerClosed",this.NO,this);this.g.subscribe("handlerError",this.OO,this);this.g.subscribe("handlerMessage",this.PO,this);qBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.NG()&&g.HG("yt-remote-session-video-id",a)},this)},Y7=function(a){$6("conn",a)},dCa=function(a,b){return new U6(X6(a.na,"/bc"),b)},Z7=function(a,b){a.P("proxyStateChange",b)},eCa=function(a){a.B=g.OD((0,g.z)(function(){Y7("Connecting timeout");
this.C(1)},a),2E4)},$7=function(a){g.QD(a.B);
a.B=window.NaN},a8=function(a){g.QD(a.L);
a.L=window.NaN},fCa=function(a){b8(a);
a.K=g.OD((0,g.z)(function(){c8(this,"getNowPlaying")},a),2E4)},b8=function(a){g.QD(a.K);
a.K=window.NaN},hCa=function(a,b){b&&($7(a),a8(a));
b==(V6(a.g)&&(0,window.isNaN)(a.B))?b&&(Z7(a,1),c8(a,"getSubtitlesTrack")):b?(a.W()&&a.bb.reset(),Z7(a,1),c8(a,"getNowPlaying"),gCa(a)):a.C(1)},iCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Vb(b.params)?a.bb.l=null:a.bb.l=b.params,a.P("remotePlayerChange"))},jCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;N7(a.bb,c,d);a.P("remoteQueueChange")},lCa=function(a,b){b.params=b.params||{};
jCa(a,b);kCa(a,b);a.P("autoplayDismissed")},kCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
L7(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.H=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.bb.g?fCa(a):b8(a);
a.P("remotePlayerChange")},mCa=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);L7(a.bb,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},nCa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.P("remotePlayerChange")},oCa=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},pCa=function(a,b){var c="true"==b.params.hasNext;
a.bb.Lf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.P("previousNextChange")},gCa=function(a){g.QD(a.I);
a.I=g.OD((0,g.z)(a.C,a,1),864E5)},c8=function(a,b,c){c?Y7("Sending: action="+b+", params="+g.xg(c)):Y7("Sending: action="+b);
a.g.sendMessage(b,c)},d8=function(a){d7.call(this,"ScreenServiceProxy");
this.cd=a;this.l=[];this.l.push(this.cd.$_s("screenChange",(0,g.z)(this.JU,this)));this.l.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.MQ,this)))},uCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ID("MDX_CONFIG")||b;g.FG&&lAa();k6();e8||(e8=new W6(b?b.loungeApiHost:void 0),DAa()&&(e8.g="/api/loungedev"));f8||(f8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",f8,void 0));qCa();var c=g8();if(!c){var d=new m7(e8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=g8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);VBa(a,d,function(a){a?h8()&&H7(h8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.UF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),i8("Initializing: "+g.xg(b)),j8.push(g.QF("yt-remote-cast2-availability-change",function(){g.UF("yt-remote-receiver-availability-change")})),j8.push(g.QF("yt-remote-cast2-receiver-selected",function(){k8(null);
g.UF("yt-remote-auto-connect","cast-selector-receiver")})),j8.push(g.QF("yt-remote-cast2-receiver-resumed",function(){g.UF("yt-remote-receiver-resumed","cast-selector-receiver")})),j8.push(g.QF("yt-remote-cast2-session-change",rCa)),j8.push(g.QF("yt-remote-connection-change",function(a){a?H7(h8(),"YouTube TV"):l8()||(H7(null,null),YBa())})),a=m8(),b.isAuto&&(a.id+="#dial"),g.GE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),i8(" -- with channel params: "+
g.xg(a)),sCa(a),c.start(),h8()||tCa())},wCa=function(){var a=vCa();
E7()&&g.IG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},vCa=function(){var a=g8().cd.$_gos();
var b=n8();b&&o8()&&(f6(a,b)||a.push(b));return vAa(a)},p8=function(){var a=xCa();
!a&&E7()&&XBa()&&(a={key:"cast-selector-receiver",name:XBa()});return a},xCa=function(){var a=vCa(),b=n8();
b||(b=l8());return g.Ja(a,function(a){return b&&b6(b,a.key)?!0:!1})},n8=function(){var a=h8();
if(!a)return null;var b=g8().ke();return g6(b,a)},rCa=function(a){i8("remote.onCastSessionChange_: "+c6(a));
if(a){var b=n8();b&&b.id==a.id?H7(b.id,"YouTube TV"):(b&&q8(),r8(a,1))}else o8()&&q8()},q8=function(){F7()?C7().stopSession():A7("stopSession called before API ready.");
var a=o8();a&&(a.disconnect(1),s8(null))},t8=function(){var a=o8();
return!!a&&3!=a.getProxyState()},i8=function(a){$6("remote",a)},g8=function(){if(!u8){var a=g.x("yt.mdx.remote.screenService_");
u8=a?new d8(a):null}return u8},h8=function(){return g.x("yt.mdx.remote.currentScreenId_")},yCa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},zCa=function(){return g.x("yt.mdx.remote.connectData_")},k8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},o8=function(){return g.x("yt.mdx.remote.connection_")},s8=function(a){var b=o8();
k8(null);a||yCa("");g.ua("yt.mdx.remote.connection_",a,void 0);f8&&((0,g.C)(f8,function(b){b(a)}),f8.length=0);
b&&!a?g.UF("yt-remote-connection-change",!1):!b&&a&&g.UF("yt-remote-connection-change",!0)},l8=function(){var a=g.NG();
if(!a)return null;var b=g8().ke();return g6(b,a)},r8=function(a,b){n8()&&n8();
yCa(a.id);var c=new X7(e8,a,m8());c.connect(b,zCa());c.subscribe("beforeDisconnect",function(a){g.UF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){o8()&&s8(null)});
s8(c)},tCa=function(){var a=l8();
a?(i8("Resume connection to: "+c6(a)),r8(a,0)):(l6(),YBa(),i8("Skipping connecting because no session screen found."))},qCa=function(){var a=m8();
if(g.Vb(a)){a=j6();var b=g.IG("yt-remote-session-name")||"",c=g.IG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},m8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},sCa=function(a){a?(g.HG("yt-remote-session-app",a.app),g.HG("yt-remote-session-name",a.name)):(g.JG("yt-remote-session-app"),g.JG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},v8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.CF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.eQ);this.o.O(b,"captionschanged",this.KO);this.o.O(b,"captionssettingschanged",this.UC);this.o.O(b,"videoplayerreset",this.Mo);this.o.O(b,"mdxautoplaycancel",this.mH);this.V=this.o.O(b,"onVolumeChange",this.mB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.zB,this);c.subscribe("remotePlayerChange",this.El,this);c.subscribe("remoteQueueChange",this.Mo,this);c.subscribe("autoplayUpNext",this.VA,
this);c.subscribe("previousNextChange",this.wB,this);c.subscribe("nowAutoplaying",this.oB,this);c.subscribe("autoplayDismissed",this.UA,this);this.suggestion=null;this.H=new g.OO(64);this.A=new g.$t(this.QC,500,this);g.M(this,this.A);this.B=new g.$t(this.RC,1E3,this);g.M(this,this.B);this.K=new t6(this.mU,0,this);g.M(this,this.K);this.C={};this.L=new g.$t(this.xD,1E3,this);g.M(this,this.L);this.I=new g.Qk(this.QM,1E3,this);g.M(this,this.I);this.N=g.y;this.UC();this.Mo();this.El()},w8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},ACa=function(a){w8(a,0);
a.A.stop();x8(a,new g.OO(64))},z8=function(a,b){if(y8(a)&&!a.D){var c=null;
b&&(c={style:a.l.yi()},g.cc(c,b));a.g.IC(a.l.ea(1).videoId,c);a.C=R7(a.g).l}},A8=function(a,b){var c=a.l.Vf();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.zj;var m=R7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};N7(m,k,l);g.t(b)&&(L7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);V7(c,"setPlaylist",q);e||T7(c,m);x8(a,new g.OO(1))},BCa=function(a,b){if(b){var c=a.l.zc("captions","tracklist",{Fy:1});
c&&c.length?(a.l.Hd("captions","track",b),a.D=!1):(a.l.pl("captions"),a.D=!0)}else a.l.Hd("captions","track",{})},y8=function(a){return R7(a.g).videoId==a.l.ea(1).videoId},x8=function(a,b){a.B.stop();
var c=a.H;if(!g.VO(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.cV(a.l,d);a.H=b;CCa(a.F,c,b)}},B8=function(a){g.V.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.Sna()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.KV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);DCa(this,g.$U(a))},DCa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.zc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},C8=function(a,b){g.JZ.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},D8=function(a){g.zV.call(this,a);
g.PG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:e6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.OO(64);this.H=0;if(!g.vM(g.X(this.g))){a=
this.g;var b=g.eI(a);b&&(b=b.uo())&&(b=new C8(a,b),g.M(this,b));b=new B8(a);g.M(this,b);g.tV(a,b.element,4)}},CCa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.aP(c,b))},E8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)q8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Vf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.jc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.zj,index:Math.max(a.g.Dz(),0),currentTime:0==f?void 0:f}}else c=null;i8("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(k8(c||null),F7()?C7().setLaunchParams(c||null):A7("setLaunchParams called before ready.")):!c&&
t8()&&h8()==b.key?g.UF("yt-remote-connection-change",!0):(q8(),k8(c||null),c=g8().ke(),(c=g6(c,b.key))&&r8(c,1))}},SAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},D6={"'":"\\'"},ECa={},rAa={aW:"atp",w0:"ska",L_:"que",VZ:"mus",s0:"sus"};
$5.prototype.gn=function(){var a=new $5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var m6,i6="",q6=n6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",KAa=n6("loadCastFramework")||n6("loadCastApplicationFramework"),UBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(t6,g.K);g.h=t6.prototype;g.h.aI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.uc:this.xa=g.rg(this.B,this.uc)};
g.h.stop=function(){this.xa&&(g.sg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();t6.Z.U.call(this)};
g.h.bI=function(){this.o?(this.xa=g.rg(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};u6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
u6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=v6.prototype;g.h.gi=null;g.h.xf=!1;g.h.mk=null;g.h.Vu=null;g.h.Sj=null;g.h.pj=null;g.h.ih=null;g.h.Ah=null;g.h.Gi=null;g.h.Pc=null;g.h.Tl=0;g.h.yf=null;g.h.Fp=null;g.h.jh=null;g.h.Qk=-1;g.h.qC=!0;g.h.Ph=!1;g.h.lr=0;g.h.Wo=null;var QAa={},y6={};g.h=v6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.eT=function(a){a=a.target;var b=this.Wo;b&&3==g.nx(a)?b.nj():this.FD(a)};
g.h.FD=function(a){try{if(a==this.Pc)a:{var b=g.nx(this.Pc),c=this.Pc.l,d=this.Pc.getStatus();if(g.sd&&!g.oc(10)||g.ud&&!g.nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.af&&!g.rx(this.Pc))break a;this.Ph||4!=b||7==c||(8==c||0>=d?this.g.tf(3):this.g.tf(2));F6(this);var e=this.Pc.getStatus();this.Qk=e;var f=g.rx(this.Pc);(this.xf=200==e)?(4==b&&B6(this),this.C?(RAa(this,b,f),g.af&&this.xf&&3==b&&(this.A.R(this.l,"tick",this.XS),this.l.start())):A6(this,f),this.xf&&!this.Ph&&(4==b?this.g.Ko(this):
(this.xf=!1,x6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.jh=3,z6(13)):(this.jh=0,z6(14)),B6(this),C6(this))}}catch(k){this.Pc&&g.rx(this.Pc)}finally{}};
g.h.XS=function(){var a=g.nx(this.Pc),b=g.rx(this.Pc);this.Tl<b.length&&(F6(this),RAa(this,a,b),this.xf&&4!=a&&x6(this))};
g.h.iS=function(a){E6((0,g.z)(this.hS,this,a),0)};
g.h.hS=function(a){this.Ph||(F6(this),A6(this,a),x6(this))};
g.h.HB=function(a){E6((0,g.z)(this.gS,this,a),0)};
g.h.gS=function(a){this.Ph||(B6(this),this.xf=a,this.g.Ko(this),this.g.tf(4))};
g.h.cancel=function(){this.Ph=!0;B6(this)};
g.h.zS=function(){this.mk=null;var a=(0,g.G)();0<=a-this.Vu?(2!=this.pj&&this.g.tf(3),B6(this),this.jh=2,z6(18),C6(this)):UAa(this,this.Vu-a)};g.h=XAa.prototype;g.h.ir=null;g.h.se=null;g.h.Xo=!1;g.h.Rx=null;g.h.wn=null;g.h.jr=null;g.h.kr=null;g.h.Le=null;g.h.xg=-1;g.h.Pk=null;g.h.sk=null;g.h.connect=function(a){this.kr=a;a=H6(this.g,null,this.kr);z6(3);this.Rx=(0,g.G)();var b=this.g.F;null!=b?(this.Pk=b[0],(this.sk=b[1])?(this.Le=1,YAa(this)):(this.Le=2,J6(this))):(Z5(a,"MODE","init"),this.se=new v6(this,void 0,void 0,void 0),this.se.gi=this.ir,w6(this.se,a,!1,null,!0),this.Le=0)};
g.h.nH=function(a){if(a)this.Le=2,J6(this);else{z6(4);var b=this.g;b.hf=b.Yg.xg;Q6(b,9)}a&&this.tf(2)};
g.h.Gq=function(a){return this.g.Gq(a)};
g.h.abort=function(){this.se&&(this.se.cancel(),this.se=null);this.xg=-1};
g.h.Qx=function(){return!1};
g.h.AB=function(a,b){this.xg=a.Qk;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.hf=this.xg;Q6(c,2);return}this.Pk=c[0];this.sk=c[1]}else c=this.g,c.hf=this.xg,Q6(c,2);else if(2==this.Le)if(this.Xo)z6(7),this.jr=(0,g.G)();else if("11111"==b){if(z6(6),this.Xo=!0,this.wn=(0,g.G)(),c=this.wn-this.Rx,!g.sd||g.oc(10)||500>c)this.xg=200,this.se.cancel(),z6(12),I6(this.g,this,!0)}else z6(8),this.wn=this.jr=(0,g.G)(),this.Xo=!1};
g.h.Ko=function(){this.xg=this.se.Qk;if(this.se.xf)0==this.Le?this.sk?(this.Le=1,YAa(this)):(this.Le=2,J6(this)):2==this.Le&&((!g.sd||g.oc(10)?!this.Xo:200>this.jr-this.wn)?(z6(11),I6(this.g,this,!1)):(z6(12),I6(this.g,this,!0)));else{0==this.Le?z6(9):2==this.Le&&z6(10);var a=this.g;a.hf=this.xg;Q6(a,2)}};
g.h.Ml=function(){return this.g.Ml()};
g.h.isActive=function(){return this.g.isActive()};
g.h.tf=function(a){this.g.tf(a)};g.h=K6.prototype;g.h.Ck=null;g.h.Qd=null;g.h.tc=null;g.h.gr=null;g.h.zn=null;g.h.hw=null;g.h.On=null;g.h.yl=0;g.h.dO=0;g.h.qd=null;g.h.ah=null;g.h.pg=null;g.h.Th=null;g.h.Yg=null;g.h.Ep=null;g.h.Cj=-1;g.h.Qy=-1;g.h.hf=-1;g.h.hj=0;g.h.Wi=0;g.h.Rh=8;var R6=new g.Cf;g.A($Aa,g.Ze);g.A(aBa,g.Ze);g.A(bBa,g.Ze);g.h=K6.prototype;g.h.connect=function(a,b,c,d,e){z6(0);this.gr=b;this.Ck=c||{};d&&g.t(e)&&(this.Ck.OSID=d,this.Ck.OAID=e);this.C?(E6((0,g.z)(this.Gw,this,a),100),fBa(this)):this.Gw(a)};
g.h.Gw=function(a){this.Yg=new XAa(this);this.Yg.ir=null;this.Yg.l=this.B;this.Yg.connect(a)};
g.h.Qx=function(){return 0==this.g};
g.h.FB=function(a){this.ah=null;iBa(this,a)};
g.h.EB=function(){this.pg=null;this.tc=new v6(this,this.o,"rpc",this.D);this.tc.gi=null;this.tc.lr=0;var a=this.hw.clone();g.Gm(a,"RID","rpc");g.Gm(a,"SID",this.o);g.Gm(a,"CI",this.Ep?"0":"1");g.Gm(a,"AID",this.Cj);L6(this,a);if(!g.sd||g.oc(10))g.Gm(a,"TYPE","xmlhttp"),w6(this.tc,a,!0,this.On,!1);else{g.Gm(a,"TYPE","html");var b=this.tc,c=!!this.On;b.pj=3;b.ih=Y5(a.clone());TAa(b,c)}};
g.h.AB=function(a,b){if(0!=this.g&&(this.tc==a||this.Qd==a))if(this.hf=a.Qk,this.Qd==a&&3==this.g)if(7<this.Rh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.tc)if(this.tc.Sj+3E3<this.Qd.Sj)N6(this),this.tc.cancel(),this.tc=null;else break a;P6(this);z6(19)}}else this.Qy=c[1],0<this.Qy-this.Cj&&37500>c[2]&&this.Ep&&0==this.Wi&&!this.Th&&(this.Th=E6((0,g.z)(this.FO,this),6E3));else Q6(this,11)}else b!=ECa.eX.g&&Q6(this,11);else if(this.tc==a&&
N6(this),!g.D(b)){c=this.B.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Cj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.On=e[2],e=e[3],null!=e?this.Rh=e:this.Rh=6,this.g=3,this.qd&&this.qd.uw(),this.hw=H6(this,this.Ml()?this.On:null,this.gr),jBa(this)):"stop"==e[0]&&Q6(this,7):3==this.g&&("stop"==e[0]?Q6(this,7):"noop"!=e[0]&&this.qd&&this.qd.tw(e),this.Wi=0)}}};
g.h.FO=function(){null!=this.Th&&(this.Th=null,this.tc.cancel(),this.tc=null,P6(this),z6(20))};
g.h.Ko=function(a){if(this.tc==a){N6(this);this.tc=null;var b=2}else if(this.Qd==a)this.Qd=null,b=1;else return;this.hf=a.Qk;if(0!=this.g)if(a.xf)1==b?(b=(0,g.G)()-a.Sj,R6.dispatchEvent(new aBa(R6,a.Gi?a.Gi.length:0,b,this.hj)),M6(this),this.A.length=0):jBa(this);else{var c=a.jh,d;if(!(d=3==c||7==c||0==c&&0<this.hf)){if(d=1==b)this.Qd||this.ah||1==this.g||2<=this.hj?d=!1:(this.ah=E6((0,g.z)(this.FB,this,a),kBa(this,this.hj)),this.hj++,d=!0);d=!(d||2==b&&P6(this))}if(d)switch(c){case 1:Q6(this,5);
break;case 4:Q6(this,10);break;case 3:Q6(this,6);break;case 7:Q6(this,12);break;default:Q6(this,2)}}};
g.h.IH=function(a){if(!g.Na(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.aU=function(a){a?z6(2):(z6(1),lBa(this,8))};
g.h.Gq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.dx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.tf=function(a){R6.dispatchEvent(new bBa(R6,a))};
g.h.Ml=function(){return!(!g.sd||g.oc(10))};
g.h=mBa.prototype;g.h.uw=function(){};
g.h.tw=function(){};
g.h.rw=function(){};
g.h.uq=function(){};
g.h.yx=function(){return{}};
g.h.isActive=function(){return!0};g.A(T6,g.K);T6.prototype.o=function(){500<this.uc&&24E4>2*this.uc&&(this.uc*=2);this.A();this.l&&this.start()};
T6.prototype.start=function(){g.au(this.g,this.uc);this.l=(0,g.G)()+this.uc};
T6.prototype.stop=function(){this.g.stop();this.l=0};
T6.prototype.isActive=function(){return this.g.isActive()};g.A(U6,mBa);g.h=U6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Jd=function(a){return this.o.Jd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Xe(this.o),pBa(this),g.Xe(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new K6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Cj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.cc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):V6(this)&&gBa(this.g,c)};
g.h.uw=function(){S6(this.l);this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)gBa(this.g,a[b])}this.P("handlerOpened")};
g.h.rw=function(a){var b=2==a&&401==this.g.hf;if(4!=a&&!b){if(6==a||410==this.g.hf)b=this.l,b.g.stop(),b.uc=500;this.l.start()}this.P("handlerError",a)};
g.h.uq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.yx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.cc(a,this.B);return a};
g.h.tw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(S6(this.l),this.l.start(),eBa(this.g)):this.P("handlerMessage",new nBa(a[0],a[1]))};
g.h.FU=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.Qd&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};W6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
W6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
W6.prototype.B=function(a){a(Error("request timed out"))};var xBa=(0,g.G)(),Z6=null,b7=Array(50),a7=-1,c7=!1;g.A(d7,g.FF);d7.prototype.ke=function(){return this.g};
d7.prototype.contains=function(a){return!!f6(this.g,a)};
d7.prototype.get=function(a){return a?g6(this.g,a):null};
d7.prototype.info=function(a){$6(this.D,a)};g.A(e7,g.FF);var FCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=e7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.KD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.QD(this.xa),this.xa=window.NaN)};
g.h.U=function(){this.stop();e7.Z.U.call(this)};
g.h.KD=function(){this.xa=window.NaN;this.g=g.lE(X6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.HU,this),onError:(0,g.z)(this.GU,this),ud:(0,g.z)(this.IU,this)})};
g.h.HU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new a6(c))};
g.h.GU=function(a){this.g=null;a.status&&404==a.status?this.l>=FCa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=FCa[this.l],this.xa=g.OD((0,g.z)(this.KD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.IU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(g7,d7);g.h=g7.prototype;g.h.start=function(){f7(this)&&this.P("screenChange");!g.IG("yt-remote-lounge-token-expiration")&&BBa(this);g.QD(this.l);this.l=g.OD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){f7(this);yBa(this,a);h7(this,!1);this.P("screenChange");b(a);a.token||BBa(this)};
g.h.remove=function(a,b){var c=f7(this);ABa(this,a)&&(h7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Ap=function(a,b,c,d){var e=f7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,h7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.QD(this.l);g7.Z.U.call(this)};
g.h.nI=function(a){f7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}h7(this,!b);b&&$6(this.D,"Missed "+b+" lounge tokens.")};
g.h.mI=function(a){$6(this.D,"Requesting lounge tokens failed: "+a)};g.A(j7,g.FF);g.h=j7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.IG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?l7(this):(this.A=(0,g.G)()+3E5,g.HG("yt-remote-fast-check-period",this.A),this.hu())};
g.h.isEmpty=function(){return g.Vb(this.g)};
g.h.update=function(){i7("Updating availability on schedule.");var a=this.C(),b=g.Kb(this.g,function(b,d){return b&&!!g6(a,d)},this);
k7(this,b)};
g.h.U=function(){g.QD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);j7.Z.U.call(this)};
g.h.hu=function(){g.QD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=EBa(this);if(g.Nb(a)){var b=X6(this.B,"/pairing/get_screen_availability");this.l=Y6(this.B,b,{lounge_token:g.Pb(a).join(",")},(0,g.z)(this.JR,this,a),(0,g.z)(this.IR,this))}else k7(this,{}),l7(this)};
g.h.JR=function(a,b){this.l=null;var c=g.Pb(EBa(this));if(g.gb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;k7(this,d);l7(this)}else this.fc("Changing Screen set during request."),this.hu()};
g.h.IR=function(a){this.fc("Screen availability failed: "+a);this.l=null;l7(this)};
g.h.fc=function(a){$6("OnlineScreenService",a)};g.A(m7,d7);g.h=m7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Ap=function(a,b,c,d){this.o.contains(a)?this.o.Ap(a,b,c,d):(a="Updating name of unknown screen: "+a.name,$6(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Va(this.g,(0,g.Gd)(this.A,function(a){return!this.contains(a)},this))};
g.h.LD=function(){return(0,g.Gd)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.MD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new e7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Xe(f);d(n7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Xe(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.KU=function(a,b,c,d){g.lE(X6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new a6(d.screen||{});if(!e.name||IBa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);IBa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(n7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
ud:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Xe(this.o);g.Xe(this.l);m7.Z.U.call(this)};
g.h.DI=function(){JBa(this);this.P("screenChange");this.l.update()};
m7.prototype.dispose=m7.prototype.dispose;g.A(p7,g.FF);g.h=p7.prototype;g.h.Lo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.qe=function(a){this.ha()||(a&&q7(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){$6(this.L,a)};
g.h.PD=function(){return null};
g.h.pu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){q7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.pu("");p7.Z.U.call(this)};g.A(r7,p7);g.h=r7.prototype;g.h.ou=function(a){if(this.g){if(this.g==a)return;q7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);LBa(this)};
g.h.Dj=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.qe()},this),(0,g.z)(function(){this.qe(Error("Failed to stop receiver app."))},this)):this.qe(Error("Stopping cast device witout session."))};
g.h.pu=g.y;g.h.U=function(){this.info("disposeInternal");g.QD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;r7.Z.U.call(this)};
g.h.JS=function(a,b){if(!this.ha())if(b){var c=g.Yw(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":KBa(this,c.screenId);break;default:q7(this,"Unknown youtube message: "+d)}}else q7(this,"Unable to parse message.")}else q7(this,"No data in message.")};
g.h.Jx=function(a,b,c,d){HBa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(q7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.OD((0,g.z)(this.Jx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.PD=function(){return this.g};
g.h.LU=function(a){this.ha()||a||(q7(this,"Cast session died."),this.qe())};g.A(s7,p7);g.h=s7.prototype;g.h.ou=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Dj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.QD(this.C);this.A?this.A.stop((0,g.z)(this.qe,this,null),(0,g.z)(this.qe,this,"Failed to stop DIAL device.")):this.qe()};
g.h.U=function(){this.g();this.g=g.y;g.QD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;s7.Z.U.call(this)};
g.h.OU=function(a){this.ha()||a||(q7(this,"DIAL session died."),this.g(),this.g=g.y,this.qe())};
g.h.Ur=function(a){this.I=e6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,NBa(this));a(b);MBa(this)}else this.D=(0,g.z)(function(){g.QD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,NBa(this));a(b);MBa(this)},this),this.C=g.OD((0,g.z)(function(){this.D()},this),100)};
g.h.UJ=function(a,b,c){HBa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Lo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Ur(b,c)},this),(0,g.z)(function(a){q7(this,"Failed to get DIAL screen: "+a);
this.Ur(b,c)},this))};g.A(t7,p7);t7.prototype.stop=function(){this.qe()};
t7.prototype.ou=g.y;t7.prototype.Dj=function(){g.QD(this.g);this.g=window.NaN;var a=g6(this.H.ke(),this.l.label);a?this.Lo(a):this.qe(Error("No such screen"))};
t7.prototype.U=function(){g.QD(this.g);this.g=window.NaN;t7.Z.U.call(this)};g.A(u7,g.FF);g.h=u7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.BB,this),(0,g.z)(this.tR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.qP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),uBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.OD,this)),this.o=PBa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.xg(a))},this)),this.P("yt-remote-cast2-availability-change",w7(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.HT=function(a,b){v7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)v7("Unsetting old screen status: "+this.g.l.friendlyName),x7(this,null)}if(a&&b){if(!this.g){c=g6(this.l.ke(),a);if(!c){v7("setConnectedScreenStatus: Unknown screen.");return}var d=OBa(this,c);d||(v7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.xg(a))},this)));
v7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);x7(this,new t7(this.l,d),!0)}this.g.pu(b)}else v7("setConnectedScreenStatus: no screen.")};
g.h.IT=function(a){this.ha()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.Dj(a):this.fc("Setting connection data without a session")};
g.h.NU=function(){this.ha()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),x7(this,null)):v7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.BB,this),(0,g.z)(this.NR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.OD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Sa(g.x("yt.mdx.remote.debug.handlers_")||[],rBa);g.Xe(this.g);u7.Z.U.call(this)};
g.h.fc=function(a){$6("Controller",a)};
g.h.CB=function(a,b){this.g==a&&(b||x7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.pR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),v7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)v7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{v7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:x7(this,
new t7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:x7(this,new s7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:x7(this,new r7(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.qP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return v7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x7(this,new s7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.UJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Ur,b))};
g.h.BB=function(a){if(!this.ha()){v7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)v7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),x7(this,new r7(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=g6(this.l.ke(),c.label);
d&&b6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(v7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Xe(this.g),this.g=new r7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.CB,this,this.g)),this.g.Dj(null));this.g.ou(a)}}};
g.h.MU=function(){return this.g?this.g.PD():null};
g.h.NR=function(a){this.ha()||(this.fc("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&x7(this,null))};
g.h.tR=function(a){v7("Receiver availability updated: "+a);if(!this.ha()){var b=w7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;w7(this)!=b&&this.P("yt-remote-cast2-availability-change",w7(this))}};
g.h.OD=function(){this.ha()||(this.o=PBa(this),v7("Updating custom receivers: "+g.xg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",w7(this)))};
u7.prototype.setLaunchParams=u7.prototype.IT;u7.prototype.setConnectedScreenStatus=u7.prototype.HT;u7.prototype.stopSession=u7.prototype.NU;u7.prototype.getCastSession=u7.prototype.MU;u7.prototype.requestSession=u7.prototype.requestSession;u7.prototype.init=u7.prototype.init;u7.prototype.dispose=u7.prototype.dispose;var D7=[];g.h=I7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";J7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+K7(this):this.H};
g.h.clone=function(){return new I7(O7(this))};g.A(Q7,g.FF);g.h=Q7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,W7(this,"play")):V7(this,"play"),U7(this,1,M7(R7(this))),this.P("remotePlayerChange")):S7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,W7(this,"pause")):V7(this,"pause"),U7(this,2,M7(R7(this))),this.P("remotePlayerChange")):S7(this,this.pause)};
g.h.JD=function(a){if(1==this.g){if(this.l){var b=R7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,W7(this,"seekTo",{newTime:a}))}else V7(this,"seekTo",{newTime:a});U7(this,3,a);this.P("remotePlayerChange")}else S7(this,g.Da(this.JD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,W7(this,"stopVideo")):V7(this,"stopVideo");var a=R7(this);a.index=-1;a.videoId="";J7(a);T7(this,a);this.P("remotePlayerChange")}else S7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=R7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){$6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){$6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V7(this,"setVolume",e)}c.muted=b;c.volume=a;T7(this,c)}else S7(this,g.Da(this.setVolume,a,b))};
g.h.IC=function(a,b){if(1==this.g){var c=R7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.cc(d,c.l));V7(this,"setSubtitlesTrack",d);T7(this,c)}else S7(this,g.Da(this.IC,a,b))};
g.h.av=function(a,b){if(1==this.g){V7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=R7(this);c.audioTrackId=b.Nb.id;T7(this,c)}else S7(this,g.Da(this.av,a,b))};
g.h.ID=function(a,b){if(1==this.g){if(a&&b){var c=R7(this);N7(c,a,b);T7(this,c)}V7(this,"previous")}else S7(this,g.Da(this.ID,a,b))};
g.h.HD=function(a,b){if(1==this.g){if(a&&b){var c=R7(this);N7(c,a,b);T7(this,c)}V7(this,"next")}else S7(this,g.Da(this.HD,a,b))};
g.h.Ww=function(){1==this.g?V7(this,"dismissAutoplay"):S7(this,this.Ww)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}Q7.Z.dispose.call(this)};
g.h.U=function(){bCa(this);this.A=null;this.B.clear();P7(this,null);Q7.Z.U.call(this)};
g.h.bv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.mC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.lR=function(a,b){this.P(a,b)};
g.h.MO=function(a){if(!a)this.Bl(null),P7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=R7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,T7(this,b)}};
g.h.Bl=function(a){$6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),cCa(this),this.P("remotePlayerChange")};
g.h.LO=function(a){a?(cCa(this),this.P("remotePlayerChange")):this.Bl(null)};
g.h.ZO=function(){var a=ZBa();a&&P7(this,a)};
g.h.fc=function(a){$6("CP",a)};g.A(X7,g.FF);g.h=X7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;L7(this.bb,m);this.A="UNSUPPORTED";Y7("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",params:g.xg(l)},a,yAa())}else Y7("Connecting without params"),
this.g.connect({},a,yAa());eCa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),Z7(this,3));X7.Z.dispose.call(this)};
g.h.U=function(){$7(this);b8(this);a8(this);g.QD(this.H);this.H=window.NaN;g.QD(this.I);this.I=window.NaN;this.o=null;g.qF(this.V);this.V.length=0;this.g.dispose();X7.Z.U.call(this);this.A=this.D=this.l=this.bb=this.g=null};
g.h.eI=function(){this.C(2)};
g.h.QO=function(){Y7("Channel opened");this.N&&(this.N=!1,a8(this),this.L=g.OD((0,g.z)(function(){Y7("Timing out waiting for a screen.");this.C(1)},this),15E3));
CAa(oBa(this.g),this.X)};
g.h.NO=function(){Y7("Channel closed");(0,window.isNaN)(this.B)?l6(!0):l6();this.dispose()};
g.h.OO=function(a){l6();(0,window.isNaN)(this.F())?(Y7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,Y7("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Z7(this,2))};
g.h.PO=function(a){a.params?Y7("Received: action="+a.action+", params="+g.xg(a.params)):Y7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Yw(a.params.devices);this.l=(0,g.H)(a,function(a){return new $5(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
hCa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
hCa(this,!1);break;case "remoteConnected":var b=new $5(g.Yw(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Qa(this.l,b);
break;case "remoteDisconnected":b=new $5(g.Yw(a.params.device));g.Ua(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":jCa(this,a);break;case "nowPlaying":lCa(this,a);break;case "onStateChange":kCa(this,a);break;case "onAdStateChange":mCa(this,a);break;case "onVolumeChanged":nCa(this,a);break;case "onSubtitlesTrackChanged":iCa(this,a);break;case "nowAutoplaying":oCa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":pCa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:Y7("Unrecognized action: "+a.action)}};
g.h.rT=function(){if(this.o){var a=this.o;this.o=null;this.bb.videoId!=a&&c8(this,"getNowPlaying")}};
X7.prototype.subscribe=X7.prototype.subscribe;X7.prototype.unsubscribeByKey=X7.prototype.Jd;X7.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?V6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
X7.prototype.getProxyState=X7.prototype.da;X7.prototype.C=function(a){Y7("Disconnecting with "+a);$7(this);this.P("beforeDisconnect",a);1==a&&l6();pBa(this.g,a);this.dispose()};
X7.prototype.disconnect=X7.prototype.C;X7.prototype.ca=function(){var a=this.bb;this.o&&(a=this.bb.clone(),N7(a,this.o,a.index));return O7(a)};
X7.prototype.getPlayerContextData=X7.prototype.ca;
X7.prototype.ka=function(a){var b=new I7(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.o=b.videoId,g.QD(this.H),this.H=g.OD((0,g.z)(this.rT,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&M7(this.bb)==M7(b)&&g.xg(this.bb.l)==g.xg(b.l)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
X7.prototype.setPlayerContextData=X7.prototype.ka;X7.prototype.W=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
X7.prototype.getOtherConnectedRemoteId=X7.prototype.W;X7.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
X7.prototype.getReconnectTimeout=X7.prototype.F;X7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
X7.prototype.getAutoplayMode=X7.prototype.Y;X7.prototype.ba=function(){return this.D||""};
X7.prototype.getAutoplayVideoId=X7.prototype.ba;X7.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.bu(a.g);a.start()}};
X7.prototype.reconnect=X7.prototype.oa;X7.prototype.fa=function(a,b){c8(this,a,b);gCa(this)};
X7.prototype.sendMessage=X7.prototype.fa;g.A(d8,d7);g.h=d8.prototype;g.h.ke=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.add=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Ap=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.cd.$_ubk(this.l[a]);this.l.length=0;this.cd=null;d8.Z.U.call(this)};
g.h.JU=function(){this.P("screenChange")};
g.h.MQ=function(){this.P("onlineScreenChange")};
m7.prototype.$_st=m7.prototype.start;m7.prototype.$_gspc=m7.prototype.KU;m7.prototype.$_gsppc=m7.prototype.MD;m7.prototype.$_c=m7.prototype.contains;m7.prototype.$_g=m7.prototype.get;m7.prototype.$_a=m7.prototype.add;m7.prototype.$_un=m7.prototype.Ap;m7.prototype.$_r=m7.prototype.remove;m7.prototype.$_gs=m7.prototype.ke;m7.prototype.$_gos=m7.prototype.LD;m7.prototype.$_s=m7.prototype.subscribe;m7.prototype.$_ubk=m7.prototype.Jd;var e8=null,f8=null,u8=null,j8=[];g.p(v8,g.K);g.h=v8.prototype;
g.h.U=function(){g.K.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.zB,this);this.g.unsubscribe("remotePlayerChange",this.El,this);this.g.unsubscribe("remoteQueueChange",this.Mo,this);this.g.unsubscribe("autoplayUpNext",this.VA,this);this.g.unsubscribe("previousNextChange",this.wB,this);this.g.unsubscribe("nowAutoplaying",this.oB,this);this.g.unsubscribe("autoplayDismissed",this.UA,this);this.g=this.F=null};
g.h.Zz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(y8(this)){if(!R7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":R7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.nj(c[0],c[1]);break;case "control_subtitles_set_track":z8(this,c[0]);break;case "control_set_audio_track":c=c[0],y8(this)&&this.g.av(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();A8(this,0==c?void 0:c);break;case "control_seek":A8(this,c[0]);break;case "control_subtitles_set_track":z8(this,c[0]);break;case "control_set_audio_track":c=c[0],y8(this)&&this.g.av(this.l.ea(1).videoId,c)}};
g.h.KO=function(a){this.K.aI(a)};
g.h.mU=function(a){this.Zz("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.UC=function(){var a=this.l.zc("captions","track");g.Vb(a)||z8(this,a)};
g.h.mB=function(a){if(y8(this)){this.g.unsubscribe("remotePlayerChange",this.El,this);var b=Math.round(a.volume);a=!!a.muted;var c=R7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.El,this)}};
g.h.eQ=function(){g.Vb(this.C)||BCa(this,this.C);this.D=!1};
g.h.zB=function(a,b){this.B.stop();2==b&&this.RC()};
g.h.El=function(){if(y8(this)){this.A.stop();var a=R7(this.g);switch(a.g){case 1081:case 1:x8(this,new g.OO(8));this.QC();break;case 1085:case 3:x8(this,new g.OO(9));break;case 1083:case 0:x8(this,new g.OO(2));this.I.stop();w8(this,this.l.ea().lengthSeconds);break;case 1084:x8(this,new g.OO(4));break;case 2:x8(this,new g.OO(4));w8(this,M7(a));break;case -1:x8(this,new g.OO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},x8(this,new g.OO(128,a))}a=R7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,BCa(this,a));a=R7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.xD()}else ACa(this)};
g.h.wB=function(){this.l.P("mdxpreviousnextchange")};
g.h.Mo=function(){y8(this)||ACa(this)};
g.h.mH=function(){this.g.Ww()};
g.h.VA=function(a){a&&(a=g.lE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.lS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.lS=function(a,b){var c=new g.PN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.oB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.UA=function(){this.l.P("mdxautoplaycanceled")};
g.h.QM=function(a,b){-1==R7(this.g).g?A8(this,a):b&&this.g.JD(a)};
g.h.xD=function(){if(y8(this)){var a=R7(this.g);this.o.Ba(this.V);a.muted?this.l.mute():this.l.Wf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.mB)}};
g.h.QC=function(){this.A.stop();if(!this.g.ha()){var a=R7(this.g);a.kb()&&x8(this,new g.OO(8));w8(this,M7(a));this.A.start()}};
g.h.RC=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(B8,g.V);B8.prototype.A=function(a){DCa(this,a.state)};g.p(C8,g.JZ);C8.prototype.I=function(){var a=this.l.zc("remote","receivers");a&&1<a.length&&!this.l.zc("remote","quickCast")?(this.F=g.jb(a,this.B,this),g.KZ(this,(0,g.H)(a,this.B)),a=this.l.zc("remote","currentReceiver"),this.sf(this.B(a)),this.enable(!0)):this.enable(!1)};
C8.prototype.B=function(a){return a.key};
C8.prototype.rf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
C8.prototype.td=function(a){g.JZ.prototype.td.call(this,a);this.l.Hd("remote","currentReceiver",this.F[a]);this.A.Ob()};g.p(D8,g.zV);g.h=D8.prototype;g.h.create=function(){uCa(g.kM(g.X(this.g)));this.C.push(g.QF("yt-remote-before-disconnect",this.GO,this));this.C.push(g.QF("yt-remote-connection-change",this.uR,this));this.C.push(g.QF("yt-remote-receiver-availability-change",this.xB,this));this.C.push(g.QF("yt-remote-auto-connect",this.sR,this));this.C.push(g.QF("yt-remote-receiver-resumed",this.rR,this));this.xB()};
g.h.load=function(){this.g.Vs();g.zV.prototype.load.call(this);this.B=new v8(this,this.g,this.l);var a=(a=zCa())?a.currentTime:0;var b=t8()?new Q7(o8(),void 0):null;0==a&&b&&(a=M7(R7(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));CCa(this,this.D,this.D);g.U_(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Ye(this.B,this.l);this.l=this.B=null;g.zV.prototype.unload.call(this);g.U_(this.g.app,5)};
g.h.U=function(){g.RF(this.C);g.zV.prototype.U.call(this)};
g.h.tl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Zz.apply(this.B,[].concat([a],g.pa(c)))};
g.h.WH=function(){return this.loaded?this.B.suggestion:null};
g.h.Lf=function(){return this.l?R7(this.l).Lf:!1};
g.h.hasNext=function(){return this.l?R7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.EM=function(){var a=R7(this.l),b=this.g.ea();return{allowSeeking:this.g.dd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+K7(a):a.A,isPeggedToLive:1>=(a.C?a.o+K7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+K7(a):a.o,seekableStart:0<a.B?a.B+K7(a):a.B}};
g.h.FM=function(){this.l&&this.l.HD()};
g.h.GM=function(){this.l&&this.l.ID()};
g.h.GO=function(a){1==a&&(this.I=this.l?R7(this.l):null)};
g.h.uR=function(){var a=t8()?new Q7(o8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Xe(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Bz(a.videoId,M7(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.xB=function(){this.F=[this.o].concat(wCa());var a=p8()||this.o;E8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.sR=function(){var a=p8();E8(this,a)};
g.h.rR=function(){this.A=p8()};
g.h.DM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?G7():E8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&G7(),!0):!1}};
g.h.HM=function(){V7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Vc=function(){return!1};g.fY.remote=D8;})(_yt_player);
